name: Simple Manual Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"

  how-you-doing:
    runs-on: ubuntu-latest
    steps:
      - name: Ask
        run: echo "How you doing?"
