name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Github Action
        run: echo "Hello this is first workflow in GitHub Action"
      - name: Bye Github Action
        run: echo "Bye gitHub Action"
      - name: fail job intentionally
        run: exit 1
