name: Validate files
on: push

jobs:
  validate-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4

      - name: validate html file
        run: test -f home.html

      - name: validate js file
        run: test -f script.js        

      - name: validate js code
        run: node --check script.js   